### ISSUE TITLE
[BUG]: Crashes to multiplayer menu when opening an RF grid with a Transmutation Interface and having a Sated Double Chest pet learned

### ISSUE THREAD

**Issue by LokiBoiuwu** [DonovanDMC/ProjectExpansion#141]
Don't know if this is the right place to report this but it took me a while to figure out what it is and I don't want more people wasting their time trying to figure out why they're crashing. Hope this helps anyone and that this is the right place. Please let me know if it isn't.

**Description**
When having a Refined Storage system set up with the Transmutation Interface set up as an external storage and having the Sated Double Chest pet learned I crashed whenever I accessed the grid.

**Minecraft Version**
1.20.1

**ProjectExpansion Version**
1.1.1

**Forge Version**
47.3.4

**Reproduction Steps**
1. Set up your RF system, with or without any disks.
 2. Add the Transmutation Interface as an external storage and have the Sated Double Chest Pet learned (might also apply to the single one.) 
 4. Open the grid and crash

**Crash Report/Logs**
[latest.log](https://github.com/user-attachments/files/17175909/latest.log)

**Other Mods**
Refined Storage
Inventory Pets
also a lot of other mods, should be in the log.

**Comment by DonovanDMC** [comment]
FYI the error on the multiplayer screen would be useful to mention since it's nowhere in the log
netty (where this error happened) swallows errors so the only mention of what actually happened is on that multiplayer screen, I don't even get a stack trace
![image](https://github.com/user-attachments/assets/e77e480c-de5a-454b-8db3-9460fe9ba6e1)
https://mclo.gs/FSF78OJ
https://mclo.gs/CIRktfD

I'm putting these here for my own future reference

**Comment by DonovanDMC** [comment]
This is a problem in inventory pets, not us
See capnkirok/Inventory-Pets#613
