### ISSUE TITLE
Divide by Zero crash

### ISSUE THREAD

**Issue by Toshy0** [DonovanDMC/ProjectExpansion#24]
When using a Hopper or other extraction method on an emc link it causes a divide by zero error in the hopper(or other block) this immediately crashes the game i dont think this is a mod interaction error as I have tried this with different items and storages 
[crash-2022-04-17_16.58.51-server.txt](https://github.com/DonovanDMC/ProjectExpansion/files/8501979/crash-2022-04-17_16.58.51-server.txt)

**Comment by James103** [comment]
Can reproduce in Minecraft 1.16.5 and Project Expansion 1.16.5-1.0.18.

To reproduce:
1. Place an EMC Link.
2. Place a hopper below the EMC link.
3. Set the EMC link to export an item that does not have an EMC value.
4. Crash - `java.lang.ArithmeticException: BigInteger divide by zero` because `cost` is zero

https://github.com/DonovanDMC/ProjectExpansion/blob/a7ae6a94033e2a230036fed99acb0ec06607d1de/src/main/java/cool/furry/mc/forge/projectexpansion/tile/TileEMCLink.java#L230-L235

**Comment by Toshy0** [comment]
This is one cause for it however i dont think it is what caused my game to crash as the two items i was using have EMC andesite alloy from the create mod which has a value around 100 and a diamond saw which is around 8000

**Comment by DonovanDMC** [comment]
Fixed

- [1.16](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.19)
- [1.15](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.17)
