### ISSUE TITLE
Arcane Transmutation Table/Tablet Crash

### ISSUE THREAD

**Issue by DonovanDMC** [DonovanDMC/ProjectExpansion#25]
These items are currently a work in progress, and do nothing different from ProjectE's transmutation tablet. They will be removed in a future version and likely added back in with more functionality later. For now, any crash reports relating to them will be labeled as a WONTFIX, just avoid them.

**Comment by DonovanDMC** [comment]
Both the tablet & table have been removed in recent versions.

- [1.16](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.19) (`1.16.5-1.0.19` and on)
- [1.15](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.17) (`1.15.2-1.0.17` and on)

**Comment by ShadwDrgn** [comment]
just curious if these are anywhere near completion because in the other projecte expansion that's not maintained seemingly there's something called this with a built in crafting grid and it's AWESOME. hoping this mod will add one and it won't be super expensive on EMC. if it's end game it's kinda no fun.

**Comment by DonovanDMC** [comment]
Haven't started, and have no plans to
