### ISSUE TITLE
Relay causes server crash with "Ticking block entity"

### ISSUE THREAD

**Issue by RoyalBingBong** [DonovanDMC/ProjectExpansion#47]
Server (SSP) crashes with "Ticking block entity" on 1.16.5-1.0.22 when a Relay ist placed in the world. The world then is corrupted in that it will crash again when trying to load in. Going back to 1.0.21 works as a fix or removing the block via other tools.

https://pastebin.com/i1jvze2v

**Comment by Kithio** [comment]
Was the Relay placed next to anything or just free standing?

**Comment by Kithio** [comment]
Problem has been fixed and will be available in next version push.

**Comment by DonovanDMC** [comment]
Fixed in latest releases
1.14: [1.0.3](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.14.4-1.0.3)
1.15: [1.0.22](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.22)
1.16: [1.0.23](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.23)
1.18: N/A
