### ISSUE TITLE
EMC Link missing textures

### ISSUE THREAD

**Issue by dBHI-zz** [DonovanDMC/ProjectExpansion#54]
Hello,

since the update today the EMC-Links seem to miss textures:
![image](https://user-images.githubusercontent.com/3235171/172040921-a415d212-0053-47ed-b2f3-48fb2e212db2.png)

Best regards,
dBHI

**Comment by DonovanDMC** [comment]
break and replace

**Comment by DonovanDMC** [comment]
this is caused by emc links being directional, I'm going to remove that and see if nothing else breaks
it'll take a bit for this to get into a release as it's just visual

**Comment by DonovanDMC** [comment]
Fixed in recent releases
1.18: [1.0.7](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.7) (note: this isn't the latest release)
1.16: [1.0.28](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.28)
1.15: [1.0.27](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.27)
1.14: [1.0.8](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.14.4-1.0.8)
