### ISSUE TITLE
Unformatted number for "not enough EMC" message when extracting from an EMC Link

### ISSUE THREAD

**Issue by James103** [DonovanDMC/ProjectExpansion#57]
As of Project Expansion 1.0.9 for Minecraft 1.18.2, when attempting to extract items from an EMC Link but without having enough EMC to extract the item, the message "You do not have enough emc to purchase this; you need %s" is displayed, where `%s` is the EMC value of the item.

However, this value is displayed raw, with no formatting whatsoever.
Example when extracting an item worth 1.23 Million EMC: "You do not have enough emc to purchase this; you need 1234567"
Corrected: "You do not have enough emc to purchase this; you need 1.23 Million"

This is because there are still some instances where `String.valueOf` is used to format a (large) EMC value, where `EMCFormat.format` should be used.

Example:
https://github.com/DonovanDMC/ProjectExpansion/blob/aab6f320c5d0a543b7e6bc3b81c24065d069284c/src/main/java/cool/furry/mc/forge/projectexpansion/item/ItemMatterUpgrader.java#L120

Non-example:
https://github.com/DonovanDMC/ProjectExpansion/blob/cd2445b6569034298bf014c523aa56edcc6b38e8/src/main/java/cool/furry/mc/forge/projectexpansion/block/entity/BlockEntityEMCLink.java#L394

**Comment by DonovanDMC** [comment]
Fixed in latest releases
1.14: [1.0.10](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.14.4-1.0.10)
1.15: [1.0.29](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.29)
1.16: [1.0.30](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.30)
1.18: [1.0.10](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.10)
