### ISSUE TITLE
Feature Idea: Crystal player's skull to fake the player's presence

### ISSUE THREAD

**Issue by ArbitraryHubris** [DonovanDMC/ProjectExpansion#58]
I'd like to have an item that can be placed on a pedestal and would make systems around a certain radius think that a player is logged in, so their personal emc account is active.  This would help greatly with chunkloaded automated processes which rely on emc links for materials.   It would be good to use the project-e pedestal for this.  A crystal replica of my skull would be a nice item to place on the pedestal.

**Comment by DonovanDMC** [comment]
I'm denying this outright as that's practically impossible to implement without some heavy coremodding which I'm not about to do

**Comment by ArbitraryHubris** [comment]
Understood.  didn't you have the ability for emc link to work offline in Sky Odyssey?

**Comment by Kithio** [comment]
The fact that the EMC Link and Transmutation Interface originally worked offline was an oversight in code,  if the owning player was offline, the EMC from them was technically speaking infinite because you can't deduct EMC from an offline player right now through ProjectE, you'd have to write a custom handler that reads and writes the players data file, which is never a safe thing to do in the first place.

**Comment by ArbitraryHubris** [comment]
Thanks for the explanation!   Also, I love the emc links and power flowers.   Thanks for the mod.
