### ISSUE TITLE
EMC Links show fluid export limit in "MB/s" instead of "mB/s"

### ISSUE THREAD

**Issue by James103** [DonovanDMC/ProjectExpansion#59]
All of the EMC links have the correct fluid import and export limits, but the units are incorrect. "MB" could be interpreted as "megabuckets", which 10^9 times the intended unit, which is millibuckets (mB).

Therefore, the following translation should instead say `Fluid Export Limit: %s mB/s`:
https://github.com/DonovanDMC/ProjectExpansion/blob/4bfff55446932bcd19cc3fd773a94ff8b08e07f7/src/generated/resources/assets/projectexpansion/lang/en_us.json#L22

Bug exists since Project Expansion 1.0.8 (commit 5fb33e4848bac5f1f8c2974e450e02ef0bc9db74).

**Comment by DonovanDMC** [comment]
Fixed in latest releases
1.14: [1.0.10](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.14.4-1.0.10)
1.15: [1.0.29](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.15.2-1.0.29)
1.16: [1.0.30](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.16.5-1.0.30)
1.18: [1.0.10](https://github.com/DonovanDMC/ProjectExpansion/releases/tag/1.18.2-1.0.10)
